name: Release

on:
  push:
    branches:
      - "main"

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npx semantic-release

  update_develop:
    name: Update develop Branch
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - name: Checkout develop Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
      - name: Git Config
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
      - name: Merge main Branch into develop (Rebase)
        run: git rebase origin/main
      - name: Push develop Branch
        run: git push
